### ISSUE TITLE
unificar codingstyle

### ISSUE THREAD

**Issue by Mel-A** [Mel-A/base-de-datos-unlam#14]
Solo si llegamos con el tiempo:

- [ ] nombres de attrs con guion bajo y sin mayuscula

- [ ] tablas en camelcase

- [ ] palabras reservadas en mayuscula ffs

**Comment by tomasdivito** [comment]
No Meli nada que ver hay que dejar variado porque asi queda obvio que lo hicimos varios ah re le decia lo mismo por aca jeje saludos Meli tkm <3
